// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhveEAQQkKkIKZSmd1hThi-DmeLFWNA3o',
    appId: '1:783122661202:web:975100679368983ddc448b',
    messagingSenderId: '783122661202',
    projectId: 'histo-patho-app',
    authDomain: 'histo-patho-app.firebaseapp.com',
    storageBucket: 'histo-patho-app.appspot.com',
    measurementId: 'G-R5Y6V3TGJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoUOQ8pdulyPxp9zWeLZutHBvtnOgy3L0',
    appId: '1:783122661202:android:73be479b88233ff2dc448b',
    messagingSenderId: '783122661202',
    projectId: 'histo-patho-app',
    storageBucket: 'histo-patho-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM9yclVxV07y0gtkN_9dx-M59MEsd7SDM',
    appId: '1:783122661202:ios:704fe43b831e8f43dc448b',
    messagingSenderId: '783122661202',
    projectId: 'histo-patho-app',
    storageBucket: 'histo-patho-app.appspot.com',
    iosBundleId: 'com.example.histoPathoApp',
  );
}
